---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: MutualAuthenticationClient

run:
  path: MutualAuthenticationClient/ci/build.sh
