---
resources:
- name: repo
  type: git
  source: &repo-source
    uri: https://github.com/pjadhav01/MutualAuthenticationSpringBoot.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: repo
    trigger: true
  - task: web-app-tests
    file: repo/MutualAuthenticationClient/ci/build.yml
