---
resources:
- name: resource-tutorial
  type: git
  source: &repo-source
    uri: https://github.com/pjadhav01/MutualAuthenticationSpringBoot.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/MutualAuthenticationClient/ci/build.yml
