---
resources:
- name: MutualAuthenticationClient
  type: git
  source:
    uri: https://github.com/pjadhav01/MutualAuthenticationSpringBoot.git

  

jobs:
- name: job-test-app
  public: true
  plan:
  - get: MutualAuthenticationClient
    trigger: true
  - task: web-app-tests
    file: MutualAuthenticationClient/ci/build.yml
